spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
    ddl-auto: none
  devtools:
    lilvereload:
      enable: true
  freemarker:
    cache: false


  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    jdbc-url: jdbc:h2:mem:recipe10000;MODE=MySQL





